package logikaijatek;

import javax.swing.JOptionPane;

public class LogikaiiJatekGUI extends javax.swing.JFrame {

    private boolean elsoKor = true;
    private boolean masodikKor = true;

    public LogikaiiJatekGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Aranybtn = new javax.swing.JButton();
        Ezustbtn = new javax.swing.JButton();
        Bronzbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Válaszd ki az egyiket! Csak az egyik mond igazat!");

        jLabel1.setText("Én rejtem a kincset");

        jLabel3.setText("Nem én rejtem a kincset!");

        jLabel4.setText("Az arany hazudik!");

        Aranybtn.setForeground(new java.awt.Color(234, 179, 16));
        Aranybtn.setText("Arany");
        Aranybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AranybtnMouseClicked(evt);
            }
        });

        Ezustbtn.setForeground(new java.awt.Color(72, 69, 69));
        Ezustbtn.setText("Ezüst");
        Ezustbtn.setToolTipText("");
        Ezustbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EzustbtnMouseClicked(evt);
            }
        });

        Bronzbtn.setForeground(new java.awt.Color(197, 107, 77));
        Bronzbtn.setText("Bronz");
        Bronzbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BronzbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Aranybtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(Ezustbtn)
                .addGap(68, 68, 68)
                .addComponent(Bronzbtn)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Ezustbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aranybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bronzbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AranybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AranybtnMouseClicked
        if (elsoKor) {
            JOptionPane.showMessageDialog(null, "Helytelen válasz, hazudtam!");
        } else if (masodikKor) {
            JOptionPane.showMessageDialog(null, "Talán majd legközelebb...!");
        }
    }//GEN-LAST:event_AranybtnMouseClicked

    private void EzustbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EzustbtnMouseClicked
        if (elsoKor) {
        JOptionPane.showMessageDialog(null, "Helytelen válasz, hazudtam!");
    } else if (masodikKor) { 
        int valasz = JOptionPane.showConfirmDialog(null, "Gratulálok megtaláltad a kincset! Ki akarod venni?", "Kincsmegszerzés", JOptionPane.YES_NO_OPTION);

        if (valasz == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "A kincs a markodban van!");
            System.exit(0);
        } else if (valasz == JOptionPane.NO_OPTION) {
            System.exit(0);
        }
    }
    }//GEN-LAST:event_EzustbtnMouseClicked

    private void BronzbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BronzbtnMouseClicked
        if (elsoKor) {
            JOptionPane.showMessageDialog(null, "Helyes válasz, igazat mondtam!");

            int valasz = JOptionPane.showConfirmDialog(null, "Meg akarod találni a kincset?", "Kincskeresés", JOptionPane.YES_NO_OPTION);

            if (valasz == JOptionPane.YES_OPTION) {
                elsoKor = false;
                masodikKor = true;
                JOptionPane.showMessageDialog(null, "Válassz megint a ládák közül, de most a kincset kell keresned!");

            } else if (valasz == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else if (masodikKor) {
            JOptionPane.showMessageDialog(null, "Talán majd legközelebb...");
        }
    }//GEN-LAST:event_BronzbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogikaiiJatekGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aranybtn;
    private javax.swing.JButton Bronzbtn;
    private javax.swing.JButton Ezustbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
