package logikaijatek;

import javax.swing.JOptionPane;

public class LogikaiiJatekGUI extends javax.swing.JFrame {

    private boolean elsoKor = true;
    private boolean masodikKor = true;

    public LogikaiiJatekGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCim = new javax.swing.JLabel();
        lblArany = new javax.swing.JLabel();
        lblEzust = new javax.swing.JLabel();
        lblBronz = new javax.swing.JLabel();
        btnArany = new javax.swing.JButton();
        btnEzust = new javax.swing.JButton();
        btnBronz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCim.setText("Válaszd ki az egyiket! Csak az egyik mond igazat!");

        lblArany.setText("Én rejtem a kincset");

        lblEzust.setText("Nem én rejtem a kincset!");

        lblBronz.setText("Az arany hazudik!");

        btnArany.setForeground(new java.awt.Color(234, 179, 16));
        btnArany.setText("Arany");
        btnArany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAranyMouseClicked(evt);
            }
        });

        btnEzust.setForeground(new java.awt.Color(72, 69, 69));
        btnEzust.setText("Ezüst");
        btnEzust.setToolTipText("");
        btnEzust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEzustMouseClicked(evt);
            }
        });

        btnBronz.setForeground(new java.awt.Color(197, 107, 77));
        btnBronz.setText("Bronz");
        btnBronz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBronzMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblCim)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblEzust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBronz)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnArany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(btnEzust)
                .addGap(68, 68, 68)
                .addComponent(btnBronz)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(lblBronz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEzust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArany, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnEzust, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArany, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBronz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAranyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAranyMouseClicked
        if (elsoKor) {
            JOptionPane.showMessageDialog(null, "Helytelen válasz, hazudtam!");
        } else if (masodikKor) {
            JOptionPane.showMessageDialog(null, "Talán majd legközelebb...!");
        }
    }//GEN-LAST:event_btnAranyMouseClicked

    private void btnEzustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEzustMouseClicked
        if (elsoKor) {
        JOptionPane.showMessageDialog(null, "Helytelen válasz, hazudtam!");
    } else if (masodikKor) { 
        int valasz = JOptionPane.showConfirmDialog(null, "Gratulálok megtaláltad a kincset! Ki akarod venni?", "Kincsmegszerzés", JOptionPane.YES_NO_OPTION);

        if (valasz == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "A kincs a markodban van!");
            System.exit(0);
        } else if (valasz == JOptionPane.NO_OPTION) {
            System.exit(0);
        }
    }
    }//GEN-LAST:event_btnEzustMouseClicked

    private void btnBronzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBronzMouseClicked
        if (elsoKor) {
            JOptionPane.showMessageDialog(null, "Helyes válasz, igazat mondtam!");

            int valasz = JOptionPane.showConfirmDialog(null, "Meg akarod találni a kincset?", "Kincskeresés", JOptionPane.YES_NO_OPTION);

            if (valasz == JOptionPane.YES_OPTION) {
                elsoKor = false;
                masodikKor = true;
                JOptionPane.showMessageDialog(null, "Válassz megint a ládák közül, de most a kincset kell keresned!");

            } else if (valasz == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else if (masodikKor) {
            JOptionPane.showMessageDialog(null, "Talán majd legközelebb...");
        }
    }//GEN-LAST:event_btnBronzMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogikaiiJatekGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogikaiiJatekGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArany;
    private javax.swing.JButton btnBronz;
    private javax.swing.JButton btnEzust;
    private javax.swing.JLabel lblArany;
    private javax.swing.JLabel lblBronz;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblEzust;
    // End of variables declaration//GEN-END:variables
}
