/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logikaijatekgui;

import javax.swing.JOptionPane;

public class LogikaijatekGui extends javax.swing.JPanel {

    public LogikaijatekGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Aranybtn = new javax.swing.JButton();
        Ezustbtn = new javax.swing.JButton();
        Bronzbtn = new javax.swing.JButton();

        jLabel1.setText("Én rejtem a kincset");

        jLabel2.setText("Válaszd ki az egyiket! Csak az egyik mond igazat!");

        jLabel3.setText("Nem én rejtem a kincset!");

        jLabel4.setText("Az arany hazudik!");

        Aranybtn.setText("Arany");
        Aranybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AranybtnMouseClicked(evt);
            }
        });
        Aranybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AranybtnActionPerformed(evt);
            }
        });

        Ezustbtn.setText("Ezüst");
        Ezustbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EzustbtnMouseClicked(evt);
            }
        });

        Bronzbtn.setText("Bronz");
        Bronzbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BronzbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aranybtn)
                                .addGap(75, 75, 75)
                                .addComponent(Ezustbtn)
                                .addGap(54, 54, 54)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Bronzbtn)
                                .addGap(10, 10, 10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aranybtn)
                    .addComponent(Ezustbtn)
                    .addComponent(Bronzbtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AranybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AranybtnMouseClicked
        JOptionPane.showMessageDialog(null,"Helytelen válasz, nem itt van a kincs!");
    }//GEN-LAST:event_AranybtnMouseClicked

    private void EzustbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EzustbtnMouseClicked
        JOptionPane.showMessageDialog(null,"Gratulálok megtaláltad a kincset!");
    }//GEN-LAST:event_EzustbtnMouseClicked

    private void BronzbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BronzbtnMouseClicked
        JOptionPane.showMessageDialog(null,"Helytelen válasz, nem itt van a kincs!");
    }//GEN-LAST:event_BronzbtnMouseClicked

    private void AranybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AranybtnActionPerformed
        if(Aranybtn.isSelected()){
            
        }
    }//GEN-LAST:event_AranybtnActionPerformed

    
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aranybtn;
    private javax.swing.JButton Bronzbtn;
    private javax.swing.JButton Ezustbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
